import { Product } from "@/core/entities/product";

export const MOCK_PRODUCTS: Product[] = [
  // 1. Haute Parfumerie (Perfumes)
  {
    id: "prod_perfume_01",
    slug: "aauroshe-royal-oud-extrait",
    title: "Royal Oud Imperial Extrait",
    subtitle: "50ml Pure Extrait de Parfum",
    description: "An intoxicating blend of 30-year aged Cambodian agarwood, Damascus rose petals, and warm amber resin.",
    longDescription: "Crafted in small limited batches, Royal Oud Imperial Extrait opens with a burst of crisp saffron and bergamot before settling into a deep, velvety heart of wild Bulgarian rose and smoky agarwood. The sillage lingers for over 24 hours on silk and skin.",
    categoryId: "cat_perfumes",
    categorySlug: "perfumes",
    categoryName: "Haute Parfumerie",
    price: 14500,
    originalPrice: 16500,
    badge: "BESTSELLER",
    thumbnail: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviewCount: 48,
    isFeatured: true,
    isNewArrival: false,
    inStock: true,
    fragranceNotes: {
      top: ["Saffron", "Italian Bergamot", "Pink Peppercorn"],
      heart: ["Damascus Rose", "Smoky Cedarwood", "Taif Jasmine"],
      base: ["Cambodian Oud", "Ambergris", "Madagascan Vanilla"],
    },
    variants: [
      {
        id: "var_p01_50",
        sku: "AUR-PRF-OUD-50",
        name: "50ml Extrait",
        price: 14500,
        stockCount: 15,
        inStock: true,
        attributes: { size: "50ml" },
      },
      {
        id: "var_p01_100",
        sku: "AUR-PRF-OUD-100",
        name: "100ml Extrait Flacon",
        price: 24000,
        originalPrice: 27000,
        stockCount: 8,
        inStock: true,
        attributes: { size: "100ml" },
      },
    ],
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "prod_perfume_02",
    slug: "aauroshe-soleil-ambre-elixir",
    title: "Soleil d'Ambre Elixir",
    subtitle: "100ml Eau de Parfum Intense",
    description: "Sun-drenched citrus blossoms kissed by golden amber and warm creamy sandalwood.",
    longDescription: "Inspired by golden hour on the French Riviera, Soleil d'Ambre envelops the wearer in shimmering solar notes, neroli blossom, and Madagascar vanilla pod.",
    categoryId: "cat_perfumes",
    categorySlug: "perfumes",
    categoryName: "Haute Parfumerie",
    price: 11900,
    badge: "NEW",
    thumbnail: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1547887537-6158d64c35b3?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviewCount: 32,
    isFeatured: true,
    isNewArrival: true,
    inStock: true,
    fragranceNotes: {
      top: ["Neroli", "Mandarin Zest", "Cardamom"],
      heart: ["Solar Jasmine", "Ylang Ylang", "Orange Blossom"],
      base: ["Golden Amber", "Mysore Sandalwood", "White Musk"],
    },
    variants: [
      {
        id: "var_p02_100",
        sku: "AUR-PRF-SOL-100",
        name: "100ml Eau de Parfum",
        price: 11900,
        stockCount: 20,
        inStock: true,
        attributes: { size: "100ml" },
      },
    ],
    createdAt: "2026-02-01T00:00:00Z",
  },

  // 2. Fine Jewellery
  {
    id: "prod_jewel_01",
    slug: "aurora-diamond-choker-18k",
    title: "Aurora Diamond Choker",
    subtitle: "18K Solid Yellow Gold & VVS Diamonds",
    description: "Architectural interlocking gold links handset with 2.4 carats of brilliant cut diamonds.",
    longDescription: "An iconic statement choker crafted in solid 18-karat yellow gold. Hand-finished with mirror polishing and secured by a hidden safety clasp.",
    categoryId: "cat_jewellery",
    categorySlug: "jewellery",
    categoryName: "Fine Jewellery",
    price: 88000,
    originalPrice: 95000,
    badge: "EXCLUSIVE",
    thumbnail: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 5.0,
    reviewCount: 19,
    isFeatured: true,
    isNewArrival: false,
    inStock: true,
    materials: ["18K Solid Gold", "2.4ct VVS1 Diamonds", "Hallmark Certified"],
    variants: [
      {
        id: "var_j01_std",
        sku: "AUR-JWL-CHK-YG",
        name: "18K Yellow Gold (16 inch)",
        price: 88000,
        stockCount: 4,
        inStock: true,
        attributes: { metal: "Yellow Gold", length: "16 inch" },
      },
      {
        id: "var_j01_rg",
        sku: "AUR-JWL-CHK-RG",
        name: "18K Rose Gold (16 inch)",
        price: 88000,
        stockCount: 3,
        inStock: true,
        attributes: { metal: "Rose Gold", length: "16 inch" },
      },
    ],
    createdAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "prod_jewel_02",
    slug: "celeste-baroque-pearl-drop-earrings",
    title: "Céleste Baroque Pearl Drops",
    subtitle: "Freshwater Pearls & Diamond Studs",
    description: "Lustrous organic baroque pearls suspended from geometric diamond studs.",
    longDescription: "Each pair of Céleste drops is unique, featuring hand-selected AAA grade baroque pearls with iridescent overtone reflections.",
    categoryId: "cat_jewellery",
    categorySlug: "jewellery",
    categoryName: "Fine Jewellery",
    price: 32000,
    badge: "ARTISANAL",
    thumbnail: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviewCount: 27,
    isFeatured: true,
    isNewArrival: true,
    inStock: true,
    materials: ["AAA Baroque Pearls", "18K Gold Vermeil", "Conflict-Free Diamonds"],
    variants: [
      {
        id: "var_j02_one",
        sku: "AUR-JWL-PRL-01",
        name: "Standard Pair",
        price: 32000,
        stockCount: 12,
        inStock: true,
        attributes: { size: "Drop 35mm" },
      },
    ],
    createdAt: "2026-02-12T00:00:00Z",
  },

  // 3. Couture Handbags
  {
    id: "prod_bag_01",
    slug: "monolith-top-handle-noir",
    title: "The Monolith Structured Bag",
    subtitle: "Full-Grain Italian Box Leather",
    description: "Clean sculptural lines with gold-plated brass lock mechanism and detachable shoulder strap.",
    longDescription: "Hand-stitched by Tuscan leather masters, The Monolith features an accordion silhouette lined in butter-soft lambskin suede.",
    categoryId: "cat_handbags",
    categorySlug: "handbags",
    categoryName: "Couture Handbags",
    price: 49500,
    originalPrice: 55000,
    badge: "BESTSELLER",
    thumbnail: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviewCount: 51,
    isFeatured: true,
    isNewArrival: false,
    inStock: true,
    materials: ["Full-Grain Calfskin", "24K Gold-Tone Hardware", "Lambskin Suede Interior"],
    variants: [
      {
        id: "var_b01_noir",
        sku: "AUR-BAG-MNO-BLK",
        name: "Obsidian Noir",
        price: 49500,
        stockCount: 7,
        inStock: true,
        attributes: { color: "Noir" },
      },
      {
        id: "var_b01_taupe",
        sku: "AUR-BAG-MNO-TPE",
        name: "Warm Greige",
        price: 49500,
        stockCount: 5,
        inStock: true,
        attributes: { color: "Greige" },
      },
    ],
    createdAt: "2026-01-20T00:00:00Z",
  },

  // 4. Designer Apparel (Clothes)
  {
    id: "prod_app_01",
    slug: "seraphina-silk-bias-cut-gown",
    title: "Seraphina Silk Crepe Gown",
    subtitle: "100% Mulberry Silk Crepe de Chine",
    description: "Fluid silhouette that drapes gracefully with an open cowl back and subtle train.",
    longDescription: "Cut on the bias for an effortless hourglass drape. Ideal for gala evenings and intimate black-tie affairs.",
    categoryId: "cat_clothes",
    categorySlug: "clothes",
    categoryName: "Designer Apparel",
    price: 36000,
    badge: "LIMITED",
    thumbnail: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviewCount: 22,
    isFeatured: true,
    isNewArrival: true,
    inStock: true,
    materials: ["100% Mulberry Silk", "French Seam Construction"],
    variants: [
      {
        id: "var_a01_s",
        sku: "AUR-APP-SER-S",
        name: "Size Small (EU 36)",
        price: 36000,
        stockCount: 6,
        inStock: true,
        attributes: { size: "S" },
      },
      {
        id: "var_a01_m",
        sku: "AUR-APP-SER-M",
        name: "Size Medium (EU 38)",
        price: 36000,
        stockCount: 8,
        inStock: true,
        attributes: { size: "M" },
      },
      {
        id: "var_a01_l",
        sku: "AUR-APP-SER-L",
        name: "Size Large (EU 40)",
        price: 36000,
        stockCount: 4,
        inStock: true,
        attributes: { size: "L" },
      },
    ],
    createdAt: "2026-02-05T00:00:00Z",
  },

  // 5. Botanical Skincare
  {
    id: "prod_skin_01",
    slug: "aauroshe-lumina-gold-cellular-serum",
    title: "Lumina 24K Cellular Nectar",
    subtitle: "30ml Radiance Youth Elixir",
    description: "Collodial 24K gold suspended in hyaluronic tri-peptides, bakuchiol, and Swiss alpine edelweiss.",
    longDescription: "A powerhouse regenerating elixir designed to firm skin architecture, boost collagen synthesis, and impart an illuminated glass skin finish.",
    categoryId: "cat_skincare",
    categorySlug: "skincare",
    categoryName: "Botanical Skincare",
    price: 8500,
    badge: "BESTSELLER",
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviewCount: 64,
    isFeatured: true,
    isNewArrival: false,
    inStock: true,
    variants: [
      {
        id: "var_s01_30",
        sku: "AUR-SKN-LUM-30",
        name: "30ml Dropper Bottle",
        price: 8500,
        stockCount: 30,
        inStock: true,
        attributes: { volume: "30ml" },
      },
    ],
    createdAt: "2026-01-01T00:00:00Z",
  },

  // 6. Prestige Cosmetics (Makeup)
  {
    id: "prod_mkup_01",
    slug: "velvet-royale-matte-lipstick",
    title: "Velvet Royale Rouge Lipstick",
    subtitle: "Hydrating Velvet Matte In Heavy Brass Casing",
    description: "Intense one-stroke pigment infused with camellia seed oil for weightless 12-hour wear.",
    longDescription: "Housed in a weighted magnetic brass case embossed with the AAUROSHE crest. Non-drying, feather-resistant couture formula.",
    categoryId: "cat_makeup",
    categorySlug: "makeup",
    categoryName: "Prestige Cosmetics",
    price: 3400,
    badge: "NEW",
    thumbnail: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 4.7,
    reviewCount: 40,
    isFeatured: false,
    isNewArrival: true,
    inStock: true,
    variants: [
      {
        id: "var_m01_01",
        sku: "AUR-LIP-01",
        name: "No. 01 Crimson Velvet",
        price: 3400,
        stockCount: 25,
        inStock: true,
        attributes: { shade: "Crimson Velvet" },
      },
      {
        id: "var_m01_02",
        sku: "AUR-LIP-02",
        name: "No. 02 Nude Cashmere",
        price: 3400,
        stockCount: 30,
        inStock: true,
        attributes: { shade: "Nude Cashmere" },
      },
    ],
    createdAt: "2026-02-14T00:00:00Z",
  },

  // 7. Luxury Eyewear (Sunglasses)
  {
    id: "prod_eye_01",
    slug: "aethel-geometric-sunglasses",
    title: "Aethel Geometric Sunglasses",
    subtitle: "Titanium & Black Havana Acetate",
    description: "Bold bevelled cat-eye geometry with 100% UVA/UVB gradient charcoal lenses.",
    longDescription: "Individually hand-polished in Sabae, Japan. Fitted with anti-reflective back coating and gold titanium hinge accents.",
    categoryId: "cat_sunglasses",
    categorySlug: "sunglasses",
    categoryName: "Luxury Eyewear",
    price: 21500,
    badge: "EXCLUSIVE",
    thumbnail: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviewCount: 18,
    isFeatured: true,
    isNewArrival: false,
    inStock: true,
    variants: [
      {
        id: "var_sg01_blk",
        sku: "AUR-SGL-AET-BLK",
        name: "Piano Black / Gradient Gray",
        price: 21500,
        stockCount: 10,
        inStock: true,
        attributes: { frame: "Black", lens: "Gradient Gray" },
      },
    ],
    createdAt: "2026-01-18T00:00:00Z",
  },

  // 8. Artisan Belts
  {
    id: "prod_belt_01",
    slug: "aauroshe-emblem-reversible-belt",
    title: "Emblem Reversible Waist Belt",
    subtitle: "Smooth Calfskin / Gilded Monogram Clasp",
    description: "Versatile 30mm reversible belt switching seamlessly between Black Noir and Saddle Cognac.",
    longDescription: "Features the sculptured AAUROSHE gold monogram buckle. Crafted with edge-burnished vegetable-tanned French box leather.",
    categoryId: "cat_belts",
    categorySlug: "belts",
    categoryName: "Artisan Belts",
    price: 16500,
    badge: "ARTISANAL",
    thumbnail: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1624222247344-550fb60583dc?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviewCount: 29,
    isFeatured: false,
    isNewArrival: false,
    inStock: true,
    variants: [
      {
        id: "var_blt01_85",
        sku: "AUR-BLT-REV-85",
        name: "Size 80/85 cm",
        price: 16500,
        stockCount: 12,
        inStock: true,
        attributes: { size: "85cm" },
      },
      {
        id: "var_blt01_95",
        sku: "AUR-BLT-REV-95",
        name: "Size 90/95 cm",
        price: 16500,
        stockCount: 9,
        inStock: true,
        attributes: { size: "95cm" },
      },
    ],
    createdAt: "2026-01-25T00:00:00Z",
  },

  // 9. Lacquer Nail Paints
  {
    id: "prod_nail_01",
    slug: "vernis-imperial-nail-lacquer-set",
    title: "Vernis Impérial Trio Set",
    subtitle: "3 x 15ml Gel-Like Glass Finish Enamels",
    description: "Curated collection of rich jewel tones: Bordeaux Noir, Royal Gold Leaf, and Cashmere Silk.",
    longDescription: "10-free non-toxic formulation with keratin peptide infusion for stronger, high-gloss salon perfection at home.",
    categoryId: "cat_nail_paints",
    categorySlug: "nail-paints",
    categoryName: "Lacquer Nail Paints",
    price: 4200,
    badge: "NEW",
    thumbnail: "https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviewCount: 35,
    isFeatured: false,
    isNewArrival: true,
    inStock: true,
    variants: [
      {
        id: "var_nl01_set",
        sku: "AUR-NAL-IMP-03",
        name: "Trio Gift Box",
        price: 4200,
        stockCount: 22,
        inStock: true,
        attributes: { pack: "Trio" },
      },
    ],
    createdAt: "2026-02-18T00:00:00Z",
  },

  // 10. Travel Pouches & Clutches
  {
    id: "prod_pch_01",
    slug: "aauroshe-quilted-velvet-vanity-pouch",
    title: "Atelier Quilted Velvet Vanity Case",
    subtitle: "Plush Emerald Velvet & Gold Hardware",
    description: "An opulent zippered vanity pouch designed to store bespoke jewellery and perfume flacons.",
    longDescription: "Lined with water-resistant silk twill. Features elasticized organizer loops, interior zipper pockets, and a signature tassel pull.",
    categoryId: "cat_pouches",
    categorySlug: "pouches",
    categoryName: "Travel Pouches & Clutches",
    price: 9800,
    badge: "ARTISANAL",
    thumbnail: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=800&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviewCount: 16,
    isFeatured: false,
    isNewArrival: false,
    inStock: true,
    variants: [
      {
        id: "var_pch01_emr",
        sku: "AUR-PCH-VLV-EMR",
        name: "Emerald Green / Gold",
        price: 9800,
        stockCount: 14,
        inStock: true,
        attributes: { color: "Emerald" },
      },
      {
        id: "var_pch01_blk",
        sku: "AUR-PCH-VLV-BLK",
        name: "Obsidian Black / Gold",
        price: 9800,
        stockCount: 11,
        inStock: true,
        attributes: { color: "Noir" },
      },
    ],
    createdAt: "2026-01-28T00:00:00Z",
  },
];
